- name: Build and package
  run: |
    xmake f -y -p android -a arm64-v8a -m release \
      --ndk=/opt/hostedtoolcache/ndk/r28c/x64

    xmake -y -m release

    mkdir -p package

    cp build/android/arm64-v8a/release/libCustomGlintColor.so \
       package/libCustomGlintColor.so

    cp assets/customglintcolor.png \
       package/customglintcolor.png

    cd package
    zip -r ../CustomGlintColor.levipack .
